// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201124023224_Initial_Database")]
    partial class Initial_Database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorMovie");

                    b.HasData(
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 3,
                            MoviesId = 2
                        },
                        new
                        {
                            ActorsId = 4,
                            MoviesId = 2
                        });
                });

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.Property<int>("DirectorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("DirectorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("DirectorMovie");

                    b.HasData(
                        new
                        {
                            DirectorsId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            DirectorsId = 2,
                            MoviesId = 1
                        },
                        new
                        {
                            DirectorsId = 3,
                            MoviesId = 2
                        },
                        new
                        {
                            DirectorsId = 4,
                            MoviesId = 2
                        });
                });

            modelBuilder.Entity("Domain.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Actor1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Actor2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Actor3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Actor4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Actor5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Actor6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Actor7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Actor8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Actor9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Actor10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Actor11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Actor12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Actor13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Actor14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Actor15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Actor16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Actor17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Actor18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Actor19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Actor20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Actor21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Actor22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Actor23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Actor24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Actor25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Actor26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Actor27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Actor28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Actor29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Actor30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Actor31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Actor32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Actor33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Actor34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Actor35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Actor36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Actor37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Actor38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Actor39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Actor40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Actor41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Actor42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Actor43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Actor44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Actor45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Actor46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Actor47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Actor48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Actor49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Actor50"
                        });
                });

            modelBuilder.Entity("Domain.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Director1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Director2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Director3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Director4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Director5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Director6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Director7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Director8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Director9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Director10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Director11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Director12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Director13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Director14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Director15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Director16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Director17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Director18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Director19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Director20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Director21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Director22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Director23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Director24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Director25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Director26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Director27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Director28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Director29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Director30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Director31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Director32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Director33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Director34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Director35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Director36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Director37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Director38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Director39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Director40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Director41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Director42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Director43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Director44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Director45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Director46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Director47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Director48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Director49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Director50"
                        });
                });

            modelBuilder.Entity("Domain.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Genre1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Genre2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Genre3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Genre4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Genre5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Genre6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Genre7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Genre8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Genre9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Genre10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Genre11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Genre12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Genre13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Genre14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Genre15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Genre16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Genre17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Genre18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Genre19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Genre20"
                        });
                });

            modelBuilder.Entity("Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 1,
                            Name = "Movie1"
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 2,
                            Name = "Movie2"
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 3,
                            Name = "Movie3"
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 4,
                            Name = "Movie4"
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 5,
                            Name = "Movie5"
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 6,
                            Name = "Movie6"
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 7,
                            Name = "Movie7"
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 8,
                            Name = "Movie8"
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 9,
                            Name = "Movie9"
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 10,
                            Name = "Movie10"
                        },
                        new
                        {
                            Id = 11,
                            GenreId = 11,
                            Name = "Movie11"
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 12,
                            Name = "Movie12"
                        },
                        new
                        {
                            Id = 13,
                            GenreId = 13,
                            Name = "Movie13"
                        },
                        new
                        {
                            Id = 14,
                            GenreId = 14,
                            Name = "Movie14"
                        },
                        new
                        {
                            Id = 15,
                            GenreId = 15,
                            Name = "Movie15"
                        },
                        new
                        {
                            Id = 16,
                            GenreId = 16,
                            Name = "Movie16"
                        },
                        new
                        {
                            Id = 17,
                            GenreId = 17,
                            Name = "Movie17"
                        },
                        new
                        {
                            Id = 18,
                            GenreId = 18,
                            Name = "Movie18"
                        },
                        new
                        {
                            Id = 19,
                            GenreId = 19,
                            Name = "Movie19"
                        },
                        new
                        {
                            Id = 20,
                            GenreId = 20,
                            Name = "Movie20"
                        });
                });

            modelBuilder.Entity("Domain.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<short>("Value")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasComment("1. Administrator; 2. BasicUser");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Login = "admin",
                            Role = (short)1
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("Domain.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.HasOne("Domain.Director", null)
                        .WithMany()
                        .HasForeignKey("DirectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Movie", b =>
                {
                    b.HasOne("Domain.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Domain.Rating", b =>
                {
                    b.HasOne("Domain.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId");

                    b.HasOne("Domain.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Domain.Movie", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
